name: sb
description: A new Flutter project.

publish_to: 'none'
version: 1.0.8+8

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  linear_gradient: ^0.1.12
  intl: ^0.17.0
  fluttertoast: ^8.0.9
  flutter_spinkit: ^5.1.0
  lottie: ^1.4.3
  http: ^0.13.5
  dio: ^4.0.6
  path_provider: ^2.0.11
  url_launcher: ^6.1.5
  connectivity_plus: ^2.3.7
  pin_code_fields: ^7.4.0
  shared_preferences: ^2.0.15
  share_plus: ^4.4.0
  upgrader: ^4.6.1
  double_back_to_close: ^2.0.0
  validators: ^3.0.0
  expandable: ^5.0.1
  onesignal_flutter: ^3.4.1
  image_picker: ^0.8.5+3
  path: ^1.8.2
  flutter_walkthrough_screen: ^2.0.2
  flutter_svg: ^1.1.5
  cached_network_image: ^3.2.2
  cupertino_icons: ^1.0.5
  carousel_slider: ^4.1.1
  awesome_dialog: ^3.0.2
  flutter_html: ^3.0.0-alpha.6
  sliding_up_panel: ^2.0.0+1
  sqflite: ^2.2.2
  syncfusion_flutter_sliders: ^20.3.61
  badges: ^2.0.3
  pusher_channels_flutter: ^1.0.3
  pull_to_refresh: ^2.0.0
  clipboard: ^0.1.3
  webview_flutter: ^2.0.4

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.9
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "launcher_icon"
  background_color: "#000000"
  ios: true
  image_path: "assets/launcherlogo.png"
  #flutter pub run flutter_launcher_icons:main

flutter_native_splash:
  color: "#2A2A2A"
  image: "assets/logo.png"
  android: true
  ios: true
  #flutter pub run flutter_native_splash:create

flutter:
  fonts:
    - family: outfit
      fonts:
        - asset: fonts/outfit_regular.ttf
    - family: outfit-bold
      fonts:
        - asset: fonts/outfit_bold.ttf
  uses-material-design: true
  assets:
    - assets/